import type { Metadata } from "next";
import { Suspense } from "react";
// src/app/layout.js
import '@/styles/globals/global.scss';
import Header from '@/src/components/Header';
import Footer from '@/src/components/Footer';
import PageWrapper from '@/components/pagewrapper/pagewrapper';
import Loading from "@/components/loading";

export const metadata: Metadata = {
  title: "Totee Block",
  description: "Generated by create next app",
 };
 
 export default function RootLayout({
  children,
 }: {
  children: React.ReactNode;
 }) {
  return (
    <html lang="ko">
      <body>
        <Header />
        <PageWrapper>
        <Suspense fallback={<Loading />}>
          {children}
          </Suspense>
        </PageWrapper>
        <Footer />
      </body>
    </html>
  );
 } 